### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by Neodork** [Neodork/SonataRedirectBundle#2]
Register the redirect router above other routers.

``` yml
cmf_routing:
    chain:
        routers_by_id:
            neodork.redirect.router: 200
            sonata.page.router: 150
            router.default: 100
```

Register the object for the Admin Dashboard:

``` yml
sonata_admin:
    dashboard:
        groups:
            sonata.admin.group.site_builder:
                label:           Site Builder
                label_catalogue: AppBundle
                icon:            '<i class="fa fa-puzzle-piece"></i>'
                items:
                    - sonata.page.admin.page
                    - sonata.page.admin.site
                    - neodork.redirect.admin.redirect
```
